<?php
require_once("WeightWatchers.php");
require_once("../healthy/Tools.php");
class Patient extends WeightWatchers{

    private $systolic, $diastolic, $pressureDescription;


    public function __construct($name, $height, $weight, $systolic, $diastolic)
    {
        parent::__construct($name, $height, $weight);

        $this->systolic=$systolic;
        $this->diastolic=$diastolic;
    }

    public function defineBloodPressureLevel(){
        $this->pressureDescription = Tools::calculatePressureDescription($this->systolic,$this->diastolic);
    }

    public function setBloodPressure( $systolic, $diastolic){
        $this->systolic=$systolic;
        $this->diastolic=$diastolic;
        $this->pressureDescription = Tools::calculatePressureDescription($this->systolic,$this->diastolic);

    }

    public function getInfo()
    {
        $temp = parent::getInfo(); // TODO: Change the autogenerated stub
        $temp = "$temp alapaine $this->systolic mmHg, yläpaine $this->diastolic mmHg, ==> eli verenpaineet: $this->pressureDescription()";
        return $temp;

    }
}